### ISSUE TITLE
python 3.8 support?

### ISSUE THREAD

**Issue by brianmedigate** [gauge-sh/tach#75]
Does this project support python 3.8? From the `pyproject.toml` it appears that it does, but the codebase uses python-3.9-style type annotations which subscript the builtin `dict` type.

```
$ tach -h
Traceback (most recent call last):
  File "/home/brianm/repos/medigator/venv/bin/tach", line 5, in <module>
    from tach.cli import main
  File "/home/brianm/repos/medigator/venv/lib/python3.8/site-packages/tach/cli.py", line 8, in <module>
    from tach.check import check, BoundaryError
  File "/home/brianm/repos/medigator/venv/lib/python3.8/site-packages/tach/check.py", line 5, in <module>
    from tach import filesystem as fs
  File "/home/brianm/repos/medigator/venv/lib/python3.8/site-packages/tach/filesystem/__init__.py", line 1, in <module>
    from tach.filesystem.service import (
  File "/home/brianm/repos/medigator/venv/lib/python3.8/site-packages/tach/filesystem/service.py", line 46, in <module>
    def _get_file_cache() -> dict[str, FileInfo]:
TypeError: 'type' object is not subscriptable
```

```
$ python -V
Python 3.8.19
```

```
$ pip show tach
Name: tach
Version: 0.2.2
...
```

**Comment by emdoyle** [comment]
Thanks for raising this!

@max-muoto fixed this :muscle: and it's now released as `0.2.3`!
